### PR TITLE
disable start_io_logging_thread if :logger is set to a Logger.new(STDOUT)

### LINKED ISSUE #21: Serverengine logging threads livelock
Hi,
We have bumped into a livelock (100% utilization of a core), with serverengine > 1.5.5, and I was able to narrow it down to exactly these lines:

https://github.com/fluent/serverengine/blob/master/lib/serverengine/server.rb#L110..L112

It seems reopening STDOUT/ERR causes some sort of a race condition and livelock? I'm not sure.

I have worked around this by specifying 'false' explicitly for both `:log_stdout` and `:log_stderr` from Sneakers. This wouldn't trigger the rewiring of output and work around this issue.

I was hoping to get more information about if you know why this happens and what is recommended to do?

Thanks!

### PR DESCRIPTION
**Pull request by frsyuki**
If :logger option is set unexpectedly, reading from STDOUT/ERR and
writing to :logger could cause infinite loop because
:logger may write data to STDOUT/ERR.

In this case, try_get_io_from_logger is unnecessary, and harmful.
Possibly fixes #21.

### CODE REVIEW

**Comment by rud** [comment]
So you mention "unexpected `:logger`" - is there documentation what would be expected instead? In general I like my processes to log to `STDOUT` and handle log storing and rotating with `svlogd` (for instance). How would I set that op without doing something unexpected?

**Comment by frsyuki** [comment]
@rud `log: "-"` documented at the bottom of https://github.com/fluent/serverengine

**Comment by rud** [comment]
@frsyuki You are absolutely right, thank you for pointing that out to me

**Comment by AlexRiedler** [comment]
:+1: :shipit:

**Pull request merged**
