### PR TITLE
Add API to generate a random path for SocketManager, and use fiddle instead of ffi

### PR DESCRIPTION
**Pull request by naritta**
Following-up #32

### CODE REVIEW

**Comment by naritta** [comment]
By the way, in Ruby2.1 for Linux, It seems to be dead lock in thread joining.
(Mac OSX or except Ruby2.1 are fine)
https://github.com/fluent/serverengine/blob/796d97b7009d6438bc0647cf18581ca83e1410ba/lib/serverengine/socket_manager_unix.rb#L84

When I added ```sleep 0.5``` in while loop in the thread, It doesn't appear.

**Comment by frsyuki** [comment]
@naritta do you mean busy loop (as commented in the commit) or dead lock (as commented here)?

**Comment by frsyuki** [comment]
why is 95af4a1 necessary?

**Comment by naritta** [comment]
I mean busy loop as commented in the commit, because I can pass the thread using sleep.

**Comment by naritta** [comment]
95af4a1 is necessary, because we can't do bind, listen or WSADuplicateSocket if we set handle nil before doing that.

**Comment by frsyuki** [comment]
oh, then that's just a bug at wrap_io_handle.

**Comment by frsyuki** [comment]
busy loop means that `@server.accept` returns an invalid value which is not false-ish. what is the value of `peer` then?

**Comment by naritta** [comment]
This is ordinal UNIXServer, so ```@server.accept``` does not return until it get request.

**Comment by frsyuki** [comment]
@naritta I updated #16.

**Pull request closed without merging**
