### PR TITLE
A new feature to specify exit codes not to restart worker processes, and stop server

### PR DESCRIPTION
**Pull request by tagomoris**
This is a proposal to change NOT to restart worker processes which exits with specified exit code.
This feature is needed to avoid cases like:
* worker processes fails to startup with unrecoverable runtime errors, like configuration errors, "plugin not found" or others
* worker processes exits normally, for the cases like "this process will stop at the end of this year".

You can check the behavior of this feature on actual processes with the command line below:
```
# process(fork), worker process exits with code 5 (5 seconds later in default)
# server handles 0 and 5 as unrecoverable code
bundle exec ruby examples/server.rb -t process -w 3 -e 5 -u 0 -u 5

# spawn, worker process exits with code 0 (5 seconds later in default)
# server handles 0 and 5 as unrecoverable code
bundle exec ruby examples/server.rb -t spawn -w 3 -e 0 -s 10 -u 0 -u 5
```
Logs for latter case:
<details>
```
I, [2016-08-25T15:30:40.314477 #21627]  INFO -- : Server stopped.
I, [2016-08-25T15:59:08.152610 #26780]  INFO -- : Starting to run Worker.
I, [2016-08-25T15:59:08.163854 #26780]  INFO -- : Stop 10 seconds later with code 0.
I, [2016-08-25T15:59:08.165475 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:08.196556 #26781]  INFO -- : Starting to run Worker.
I, [2016-08-25T15:59:08.196635 #26781]  INFO -- : Stop 10 seconds later with code 0.
I, [2016-08-25T15:59:08.197315 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:08.208610 #26782]  INFO -- : Starting to run Worker.
I, [2016-08-25T15:59:08.208725 #26782]  INFO -- : Stop 10 seconds later with code 0.
I, [2016-08-25T15:59:08.209260 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:09.166832 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:09.201788 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:09.209471 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:10.169705 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:10.204142 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:10.209852 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:11.170360 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:11.206968 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:11.210619 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:12.172495 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:12.210954 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:12.213858 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:13.177898 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:13.211498 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:13.216946 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:14.179521 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:14.213264 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:14.219620 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:15.183492 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:15.218210 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:15.220865 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:16.187969 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:16.222704 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:16.223611 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:17.189113 #26780]  INFO -- : Awesome work!
I, [2016-08-25T15:59:17.223782 #26781]  INFO -- : Awesome work!
I, [2016-08-25T15:59:17.223918 #26782]  INFO -- : Awesome work!
I, [2016-08-25T15:59:18.192163 #26780]  INFO -- : Exitting with code 0
I, [2016-08-25T15:59:18.195514 #26779]  INFO -- : Worker 0 finished unexpectedly with status 0
I, [2016-08-25T15:59:18.226712 #26782]  INFO -- : Exitting with code 0
I, [2016-08-25T15:59:18.226712 #26781]  INFO -- : Exitting with code 0
I, [2016-08-25T15:59:18.231249 #26779]  INFO -- : Worker 1 finished unexpectedly with status 0
I, [2016-08-25T15:59:18.231476 #26779]  INFO -- : Worker 2 finished unexpectedly with status 0
I, [2016-08-25T15:59:18.231625 #26779]  INFO -- : Server stopped.
```
</details>

### CODE REVIEW

**Comment by tagomoris** [comment]
The only point to be considered is: Server and Supervisor will stop with exit code 0 with this feature.
I want them to stop with the same exit code with workers exitted, but it requires some more abnormal hacks, I think.

**Comment by frsyuki** [comment]
Sounds good idea to have this option. LGTM 👍  Let's merge.
I think it would be nicer if we can configure servers so that if at least one worker exits with unrecoverable exit code because it can avoid degraded situation where some workers stopped with unrecoverable exit code but the other workers are kept restarting.

**Comment by frsyuki** [comment]
about exit code of server and supervisor processes, I think a possible implementation is to use exception as like `Gem::SystemExitException` does. `MultiWorkerServer#run` (or `#keepalive_workers` will be able to tell exit code to `Supervisor#start_server` and `Daemon#daemonize_with_double_fork`.

**Comment by tagomoris** [comment]
@frsyuki Ah, it's just raise an instance of SystemExit error. I got it.

**Comment by tagomoris** [comment]
Log with `:stop_immediately_at_unrecoverable_exit`:
```
$ bundle exec ruby examples/server.rb -t spawn -i -r -w 3 -e 0 -s 20 -u 0 -u 5

I, [2016-08-25T17:36:51.783071 #45421]  INFO -- : Starting to run Worker.
I, [2016-08-25T17:36:51.783203 #45421]  INFO -- : Stop 9 seconds later with code 0.
I, [2016-08-25T17:36:51.784866 #45421]  INFO -- : Awesome work!
I, [2016-08-25T17:36:51.810987 #45423]  INFO -- : Starting to run Worker.
I, [2016-08-25T17:36:51.811117 #45423]  INFO -- : Stop 10 seconds later with code 0.
I, [2016-08-25T17:36:51.811627 #45423]  INFO -- : Awesome work!
I, [2016-08-25T17:36:51.812856 #45424]  INFO -- : Starting to run Worker.
I, [2016-08-25T17:36:51.812932 #45424]  INFO -- : Stop 4 seconds later with code 0.
I, [2016-08-25T17:36:51.813435 #45424]  INFO -- : Awesome work!
I, [2016-08-25T17:36:52.785976 #45421]  INFO -- : Awesome work!
I, [2016-08-25T17:36:52.814476 #45423]  INFO -- : Awesome work!
I, [2016-08-25T17:36:52.817337 #45424]  INFO -- : Awesome work!
I, [2016-08-25T17:36:53.787921 #45421]  INFO -- : Awesome work!
I, [2016-08-25T17:36:53.818300 #45423]  INFO -- : Awesome work!
I, [2016-08-25T17:36:53.818330 #45424]  INFO -- : Awesome work!
I, [2016-08-25T17:36:54.792451 #45421]  INFO -- : Awesome work!
I, [2016-08-25T17:36:54.823526 #45424]  INFO -- : Awesome work!
I, [2016-08-25T17:36:54.823526 #45423]  INFO -- : Awesome work!
I, [2016-08-25T17:36:55.792677 #45421]  INFO -- : Awesome work!
I, [2016-08-25T17:36:55.826370 #45423]  INFO -- : Awesome work!
I, [2016-08-25T17:36:55.826496 #45424]  INFO -- : Exitting with code 0
I, [2016-08-25T17:36:55.830534 #45420]  INFO -- : Worker 2 finished unexpectedly with status 0
I, [2016-08-25T17:36:55.830957 #45420]  INFO -- : Received graceful stop
I, [2016-08-25T17:36:56.332330 #45420]  INFO -- : Received graceful stop
I, [2016-08-25T17:36:56.793112 #45421]  INFO -- : Exitting
I, [2016-08-25T17:36:56.806733 #45420]  INFO -- : Worker 0 finished with status 0
I, [2016-08-25T17:36:56.806934 #45420]  INFO -- : Received graceful stop
I, [2016-08-25T17:36:56.807091 #45420]  INFO -- : Received graceful stop
I, [2016-08-25T17:36:56.826866 #45423]  INFO -- : Exitting
I, [2016-08-25T17:36:56.840247 #45420]  INFO -- : Received graceful stop
I, [2016-08-25T17:36:56.840479 #45420]  INFO -- : Worker 1 finished with status 0
I, [2016-08-25T17:36:56.840632 #45420]  INFO -- : Received graceful stop
I, [2016-08-25T17:36:56.840757 #45420]  INFO -- : Received graceful stop
I, [2016-08-25T17:36:56.840911 #45420]  INFO -- : Server stopped.
```

**Comment by tagomoris** [comment]
Here's process exit code test logs.

Foreground, with supervisor:
```
$ bundle exec ruby examples/server.rb -t spawn -i -r -w 3 -e 3 -s 20 -u 0 -u 5 -u 3 -f -x
$ echo $?
3
```

Foreground, without supervisor:
```
$ bundle exec ruby examples/server.rb -t spawn -i -r -w 3 -e 3 -s 20 -u 0 -u 5 -u 3 -f 
$ echo $?
3
```

**Comment by tagomoris** [comment]
@frsyuki I added some fix for points mentioned in your comments.
Could you check code once again? (and merge this if you are ok)

**Comment by frsyuki** [comment]
Nice. Looks good 👍

**Comment by tagomoris** [comment]
Merged.

**Pull request merged**
