### PR TITLE
Adding fence for safe

### PR DESCRIPTION
**Pull request by tagomoris**
The code of ServerEngine has many points not good. For example:

* ProcessManager and classes of ProcessManager::* are tightly coupled by sharing instance of ProcessManager, but there are no reason to do it
* All modules are loaded via autoload, but it makes code and dependency between files unclear
* Etc module is used but it's unavailable in Windows, so it should be separated from main code

I fixed these things (mainly for following fixes to fix process control on Windows platform).
I also added an example script to run ServerEngine with SocketManager actually to show it works well with each worker types.

### CODE REVIEW

**Comment by tagomoris** [comment]
@frsyuki @naritta could you check this change?

**Comment by tagomoris** [comment]
I will re-create some pull requests for this change per commits after merging #50.

**Comment by frsyuki** [comment]
Good job. It looks good improvement overall.
2 comments:

* Daemon has some backward incompatibility. Changes look like fair to bring better organization. It assumes that size of users of ServerEngine is small enough to break compatibility here. So we should at least increment major version at the next release.
* I can't find strong benefits to separate classes into lib/serverengine/monitor.rb file compared to having monitor classes scoped in xxx_worker_server.rb files. But both of them are possible options. So let's merge.

**Comment by tagomoris** [comment]
I created #52, #53, #54, #56, #57, #58 and #59. (57, 58 and 59 are based on 56) from this pull-request by splitting commits.
I didn't created changes for monitor... it's just for readability, and I agree that there aren't strong benefits.

@frsyuki I'll merge these changes next by next some days later. Please comment on these if you find something to be mentioned about.

**Pull request closed without merging**
